version: '3.9'

volumes:
  postgres_data:

services:
  postgres:
    container_name: db_service
    image: postgres:15.3-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - 'postgres_data:${DB_DATA}'
    ports:
      - '${HOST_DB_PORT}:5432'

  app_worker_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_worker_server
    stdin_open: true
    tty: true
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ./src:/app/src
    ports:
      - '${APP_PORT}:3000'
