version: '3.9'

volumes:
  app_db_data:

services:
  app_db:
    container_name: app_db
    image: postgres:15.3-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - 'app_db_data:${DB_DATA}'
    ports:
      - '${DB_PORT}:5432'

  app_worker_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_worker_server
    stdin_open: true
    tty: true
    env_file: .env
    depends_on:
      - app_db
    volumes:
      - ./:/app
    ports:
      - '${APP_PORT}:3000'
